FROM node:20-bullseye-slim
WORKDIR /usr/src/app
# Install dependencies required for Puppeteer's Chromium
RUN apt-get update && apt-get install -y wget ca-certificates fonts-liberation libasound2 libatk1.0-0 libc6 libdbus-1-3 libgconf-2-4 libgtk-3-0 libnspr4 libnss3 libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxrandr2 libxss1 libxtst6 libgbm1 lsb-release xdg-utils --no-install-recommends && rm -rf /var/lib/apt/lists/*
COPY pw_check.js ./
RUN npm init -y && npm i puppeteer --no-audit --no-fund
CMD ["node", "pw_check.js"]
